import os


env = Environment()

def RGlob(pattern):
        (directory, pattern) = os.path.split(pattern)
	print 'RGlob dir=' , directory ,"pat=", pattern
        result = []
	for file in os.listdir(directory):
		print 'dir=',directory,'file=',file
		if file.endswith('.cpp'):
			result.append(os.path.join(directory,file))
		if os.path.isdir(os.path.join(directory,file)):
			innerResults = RGlob(os.path.join(directory,file,pattern))
			result.extend( innerResults)
        return result;

def ChangeFirstDir(srcs):
	out = []
	for x in srcs:
		value = x.split('/')
		value[0] = 'obj'
		l = os.path.join(*value)
		print "----------------------",l,"----------------------"
		out.append(os.path.join(*value))
	return out

srcs = RGlob('src/*.cpp')
print '------------------------' ,srcs
VariantDir('obj','src')
srcs = ChangeFirstDir(srcs)
hello = env.Program(target = 'helloworld', source = srcs)




#print 	'TYPE - ENV - ',type(env)  # type - return the type of varibale
#print '11111-', env.GetLaunchDir()
#print 'def', env.Configure(self, args, kw)
#print help(env) ,
  # dir - return the all funcition of var (hello)






